### PR TITLE
fixes for back-button issues

### PR DESCRIPTION
**Pull request by ajans**
fixes back-button issues #72, #75, #82 and #84
confirmation pending from OP for #84

### CODE REVIEW

**Comment by ajans** [comment]
OP of #84 confirmed the fix to be working.

**Comment by TPeterW** [comment]
Hi, sorry for taking so long, the bug goes like this:

Click on the edit text area while the search results are not shown, then click on the arrow to hide/fold the results, there will be a double collapsing.

**Comment by JusticeM** [comment]
Add // android:noHistory="true"
In layout file in quinny898.persistentsearch

**Comment by TPeterW** [comment]
Sorry, that didn't help

**Comment by CristianRP** [comment]
My fast solution.
Paste it into your activity with SearchBox
`@Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.KEYCODE_BACK) {
            try {
                Log.e("error_Back", "error on key back");
            } catch (ClassCastException ce) {
                Log.e("error_Back", "error on key back");
            }
        }
        return true;
    }
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            //preventing default implementation previous to android.os.Build.VERSION_CODES.ECLAIR
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }`

**Comment by TPeterW** [comment]
This seems a lot like change made in #76, I'll check again

**Review by ShreyashPromact — COMMENTED** [review]
Is it merged? Is it resolved back button issue?

**Comment by ShreyashPromact** [comment]
I would like to know whether it resolved the issue or not.

**Pull request closed without merging**
