### PR TITLE
Added an OptionsMenu-Overflow like button to SearchBox

### PR DESCRIPTION
**Pull request by randombyte-developer**
Hi!

You can activate the OverflowMenu with [setOverflowMenu(int menuResId)](https://github.com/randombyte-developer/PersistentSearch/commit/fc0db5610e9287c506b31a697934e2f4e12e5478#diff-37bce77f6d1d88088a3a6a8da4e46229R358) and attach a listener with [setMenuListener(Listener listener)](https://github.com/randombyte-developer/PersistentSearch/commit/fc0db5610e9287c506b31a697934e2f4e12e5478#diff-37bce77f6d1d88088a3a6a8da4e46229R364).

Screencapture of the sample app in this pull request:
device-2015-07-01-105513

### CODE REVIEW

**Comment by randombyte-developer** [comment]
Merged changes from upstream. So it could be merged again.

**Comment by Quinny898** [comment]
How many of the changes are required? Unless you merge upstream changes I can't merge this

**Comment by randombyte-developer** [comment]
I will merge again when I have time.

**Comment by randombyte-developer** [comment]
@Quinny898 Ready to be merged into master

**Comment by TPeterW** [comment]
Any chance this would support showAsAction?

**Comment by randombyte-developer** [comment]
You can try implementing it yourself and opening a pull request.

**Pull request merged**
